version: "3.9"

services:
  db:
    image: mysql:5.7
    container_name: godb
    ports:
      - "33066:3306"
    volumes:
      - "./database:/docker-entrypoint-initdb.d"
    restart: always
    environment:
      
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: godb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass

  api:
    image: goo_v1
    build:
      dockerfile: ./dockers/Gockerfile
    container_name: gopi
    volumes:
      - .:/opt/app/api
    environment:
      DBUSER: user
      DBPASS: pass
      DBNAME: godb
    depends_on:
      - "db"
    ports:
      - "9999:9999"